### ISSUE TITLE
ColReorder is only ordening th

### ISSUE THREAD

**Issue by waiting-for-dev** [DataTables/ColReorder#4] opened 2012-12-21 19:12 UTC
I'm using master branch, and right now ColReorder is just ordering `th` elements, leaving unconnected columns heads with its body. Tested in firefox and chrome.

**Comment by DataTables** [comment] 2015-04-01 13:51
Going to close as a duplicate of #12. Although this issue was opened first, the other is a little more descriptive about colspan / rowspan.

**Closed by DataTables** 2015-04-01 13:51 UTC
