### ISSUE TITLE
Sorting table with columns with data-sort attribute after reorder causes "Requested unknown parameter" error

### ISSUE THREAD

**Issue by jaseczka** [DataTables/ColReorder#39] opened 2015-06-10 23:20 UTC
If a table has a column "X" that is sorted based on data-sort attributes and columns are reordered in such way that column "X" changes position, sorting on any column causes following error: "DataTables warning: table id=example - Requested unknown parameter '[object Object]' for row 0. For more information about this error, please see http://datatables.net/tn/4"

Example:
http://live.datatables.net/lezujoya/
1. Drag Office after Age
2. Try to sort on any column

**Comment by DataTables** [comment] 2015-06-11 08:41
Thanks for this. I need to do some work on ColReorder and I'll look into this when I do.

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment] 2015-10-22 09:07
I'm bitten by the same bug, but in a different way. I have a webpage which contains a table with static data, so an html table like jaseczka. However, I then update the table with an ajax request to refresh the data. 

If the first column definition in my datatable looks like "columns": [ { "data": { "_": "departure.time" } }, ... then the bug does not show. However, when I change the first column definition to "columns": [ { "data": { "_": "departure.time", "sort": "departure.hour" } }, ... so that the column gets sorted by hour of depature (0-23) then I also get the error message "DataTables warning: table id=example - Requested unknown parameter '[object Object]' for row 0. For more information about this error, please see http://datatables.net/tn/4"

So this is not related to data-sort/order html5 element but a general problem when sorting. However note that this only is a problem for the FIRST column (in my case). With the second, third and nth column the same sorting code (of course with different key name, like arriva.time/hour) works fine.

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment] 2015-10-22 10:17
Workaround to fix: Add an empty column as the very first column. This will make the previously first column the second column and the problem is resolved, because it only appears on the very first column.

BTW: I have set ColReorder to false, so I think this is not related to reordering, but maybe orthogonal data?

**Comment by DataTables** [comment] 2015-10-22 13:24
If you have ColReorder disabled that it isn't the same issue. Could you post a support request in the [forums](//datatables.net/forums) with a link to the issue so it can be debugged please.

**Comment by eli-collins** [comment] 2016-01-12 05:56
I ran into something similar, and think I've tracked this down.  I've posted pr #50 which seems to fix this problem for me, and for the example js bin.

**Comment by DataTables** [comment] 2016-02-09 16:41
This will be fixed with the release of DataTables 1.10.11 due to [this commit](https://github.com/DataTables/DataTablesSrc/commit/f8e4a4640224aa6fd61f3795d9eb9d30d39f7773). The release will be later this week.

**Closed by DataTables** 2016-02-09 16:41 UTC
