### ISSUE TITLE
dataTable.DataTable().colReorder undefined after upgrading to 1.3.3

### ISSUE THREAD

**Issue by thejavatar** [DataTables/ColReorder#65] opened 2017-04-18 13:12 UTC
Hi,

First of all great plugin, thanks!

After the upgrade to 1.3.3 when executing following code:

`$("#dataTable").DataTable().colReorder.order();`

colReorder is `undefined`. Data table is created with `"colReorder": true,` option. I am surprised to see this change of behaviour since none of the changes introduced after version 1.3.2 indicates what could be the cause of this.

Regards,
Lukasz

**Comment by DataTables** [comment] 2017-04-18 13:23
Have you got a link to a page showing the issue? I just [put together this little example](http://live.datatables.net/jozumupa/1/edit).

**Comment by thejavatar** [comment] 2017-04-20 08:43
Just to let you know I try to replicate the error in JS Bin  but so far to no avail. Will send an update once done.

**Comment by vonnieda** [comment] 2017-06-06 22:06
I believe this is likely due to the trailing comma that showed up in 1.3.3 and seemed to have been fixed in https://github.com/DataTables/ColReorder/commit/1bb4257e8497af58871ae0d58f5b9dede48a1abd. The root cause is that dataTables.colReorder.min.js in bower is 0 bytes. I suspect that however you go about generating and deploying that file choked on on the trailing comma and then the 0 byte file got deployed.

```
> bower install datatables.net-colreorder
datatables.net-colreorder#1.3.3 bower_components/datatables.net-colreorder
├── datatables.net#1.10.15
└── jquery#3.2.1

> ls -al bower_components/datatables.net-colreorder/js
total 72
drwxr-xr-x  4 jason  staff    136 Apr 17 10:10 .
drwxr-xr-x  7 jason  staff    238 Jun  6 17:02 ..
-rwxr-xr-x  1 jason  staff  35954 Apr 17 10:10 dataTables.colReorder.js
-rw-r--r--  1 jason  staff      0 Apr 17 10:10 dataTables.colReorder.min.js
```

Workaround is to to downgrade to 1.3.2 or use the non-minified version.

**Comment by DataTables** [comment] 2017-06-07 08:41
Thanks for pointing that out! I'll tag and release 1.3.4 shortly with a correctly building minified file.

Somewhat related, it looks like npm doesn't include the min file for some reason, so I'll check that out as well.

**Comment by MufidJamaluddin** [comment] 2020-04-29 23:49
I've same issue.

Unhandled Rejection (TypeError): Cannot read property '_colReorder' of undefined
ColReorder

.../node_modules/datatables.net-colreorder/js/dataTables.colReorder.js:375

**Comment by DataTables** [comment] 2020-04-30 07:50
@MufidJamaluddin - Can you link to a test page showing the issue please? The current release of ColReorder is 1.5.2 - I must have forgotten to close this issue when I tagged 1.3.4.

**Closed** 2023-12-20 17:20 UTC
